apiVersion: apps/v1
kind: Deployment
metadata:
  name: lachyr-wk10-deployment
  labels:
    app: lachyr-wk10-app
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: lachyr-wk10-node
          image: lachyr/sit323wk10
          ports:
            - containerPort: 3040
