apiVersion: v1
kind: Pod
metadata:
  name: lachyr-wk10-pod
  labels:
    tier: frontend
spec:
  containers:
    - image: lachyr/sit323wk10
      name: lachyr-wk10-app
      ports:
        - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
