apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lachyr-wk10-replicaset
  labels:
    app: lachyr-wk10-app
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: mynode
          image: lachyr/nodewebappwk6
          ports:
            - containerPort: 3040
